apiVersion: v2
name: flink
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
    - bitnami-common
    version: 2.x.x
  - name: flink
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.x.x
version: 2.0.1
description: Apache Flink is a framework and distributed processing engine for stateful
  computations over unbounded and bounded data streams.
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/flink/img/flink-stack-220x234.png
