{{- if .Values.route.kibana.enabled }}
{{- $domain := .Values.route.kibana.domainSuffix }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  host: {{ .Values.route.kibana.host }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.route.insecureEdgeTerminationPolicy }}
    termination: {{ .Values.route.termination }}
  to:
    kind: Service
    {{- if eq .Release.Name "kibana" }}
    name: kibana
    {{- else }}
    name: {{ .Release.Name }}-kibana
    {{- end }}
    weight: 100
  wildcardPolicy: None
{{- end }}
