apiVersion: v1
name: openldap
version: 1.5.0-dev
appVersion: dev
description: An open source implementation of the Lightweight Directory Access Protocol, which is a vendor-neutral, industry standard application protocol for accessing and maintaining distributed directory information services over an Internet Protocol (IP) network.
keywords:
- docker
- openldap
home: https://www.openldap.org/
icon: https://www.openldap.org/images/headers/LDAPworm.gif
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/openldap
maintainers:
- name: Alvaro Gonzalez
  email: alvaro.gonzalez@csc.fi
