apiVersion: v2
name: matomo
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
    - bitnami-common
    version: 2.x.x
  - name: matomo
    version: 10.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
description: Matomo Helm Chart for Rahti platform
  Link to the repo https://github.com/CSCfi/helm-charts
version: 2.5.1
sources:
- https://github.com/CSCfi/helm-charts
icon: https://avatars.githubusercontent.com/u/698038?s=280&v=4
