apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openldap
    spec:
      volumes:
        - name: ldap-data
          persistentVolumeClaim:
            claimName: openldap-pvc
        - name: init-ldif
          configMap:
            name: openldap-init-ldif
        - name: schema-ldif
          configMap:
            name: openldap-schema-ldif
      {{- if .Values.build.enabled }}
      serviceAccount: build-reader
      initContainers:
        - name: wait-for-build
          image: quay.io/openshift/origin-cli:4.16
          command:
            - sh
            - -c
            - oc wait --for=jsonpath='{.status.phase}'=Complete build -l buildconfig={{ .Values.build.image.repository }} --timeout=90s
      {{- end }}
      containers:
        - name: openldap
          image: "{{ .Values.build.image.registry }}/{{ .Release.Namespace }}/{{ .Values.build.image.repository }}:{{ .Values.build.image.tag }}"
          env:
            - name: LDAP_PORT_NUMBER
              value: "1389"
            - name: LDAP_LDAPS_PORT_NUMBER
              value: "1636"
            - name: LDAP_ADMIN_USERNAME
              value: {{ .Values.ldap.admin.user }}
            - name: LDAP_ADMIN_PASSWORD
              value: {{ .Values.ldap.admin.password }}
            - name: LDAP_USERS
              value: {{ .Values.ldap.users.user }}
            - name: LDAP_PASSWORDS
              value: {{ .Values.ldap.users.password }}
            - name: LDAP_ROOT
              value: dc=example,dc=org
            - name: LDAP_ADMIN_DN
              value: cn=admin,dc=example,dc=org
            - name: LDAP_LOGLEVEL
              value: "2"
            - name: LDAP_CUSTOM_SCHEMA_DIR
              value: /schemas
            - name: BITNAMI_DEBUG
              value: "true"
          volumeMounts:
            - name: ldap-data
              mountPath: /bitnami/openldap
            - name: init-ldif
              mountPath: /ldifs/
            - name: schema-ldif
              mountPath: /schemas/
      restartPolicy: Always
